host:
  ip: 127.0.0.1
server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/haha?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: dangerous
    driver-class-name: com.mysql.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 2048MB
      max-request-size: 2048MB

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xusenme.model
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

email:
  serverEmailUser: 956532577@qq.com
  serverEmailPassword: nwyssbkyihrqbbbd

user:
  defaultSize: 50 #单位G
  expired: 1440
  jwtKey: haha

fastdfs:
#  url: 47.101.205.211:80
  url: localhost:80